manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: george-norton
      url-base: https://github.com/george-norton
    - name: efogdev
      url-base: https://github.com/efogdev
    - name: nuovotaka
      url-base: https://github.com/nuovotaka
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
#    - name: zmk-pmw3610-driver
#      remote: efogdev
#      revision: main
#    - name: zmk-driver-pmw3360
#      remote: george-norton
#      revision: v0.3
#    - name: zmk-behavior-sensor-attr-cycle
#      remote: george-norton
#      revision: v0.3
#    - name: zmk-pointing-acceleration-alpha
#      remote: nuovotaka
#      revision: main
  self:
    path: config
